name = "nocodb"
main = "dist/index.js"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]
[vars]
BASE_URL = "https://dxp2800-lsl-f9cu.cn45.ug.link/"
PORT = "40515"
USERNAME = "lsl"

[[kv_namespaces]]
binding = "UGLINK_CACHE"
id = "935a6de712e042718a968160f9a7affb"  # Replace with your actual KV namespace ID from Cloudflare dashboard

[observability.logs]
enabled = true
